# Generated by Django 5.2.6 on 2025-11-17 15:32

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hackathon',
            fields=[
                ('hackathon_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('details', models.TextField()),
                ('registration_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('required_skills', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'hackathons',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HackathonTeam',
            fields=[
                ('team_id', models.AutoField(primary_key=True, serialize=False)),
                ('team_name', models.CharField(max_length=255)),
                ('team_members', models.TextField(default='', help_text='Comma-separated member names')),
            ],
            options={
                'db_table': 'hackathon_teams',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Roadmap',
            fields=[
                ('roadmap_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'roadmaps',
                'ordering': ['roadmap_id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RoadmapStep',
            fields=[
                ('step_id', models.AutoField(primary_key=True, serialize=False)),
                ('step_number', models.PositiveIntegerField()),
                ('step_content', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'roadmap_steps',
                'ordering': ['step_number'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('profile_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=255)),
                ('education', models.CharField(blank=True, max_length=255, null=True)),
                ('degree', models.CharField(blank=True, max_length=255, null=True)),
                ('skills', models.TextField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('work_experience', models.TextField(blank=True, null=True)),
                ('user_interest', models.TextField(blank=True, null=True)),
                ('industry', models.CharField(blank=True, max_length=255, null=True)),
                ('career_goals', models.TextField(blank=True, null=True)),
                ('time_frame', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'user_profile',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserRoadmapProgress',
            fields=[
                ('progress_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_step_progress',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserSelectedRoadmap',
            fields=[
                ('user_roadmap_id', models.AutoField(primary_key=True, serialize=False)),
                ('selected_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user_selected_roadmaps',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Internships',
            fields=[
                ('internship_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_id', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('duration', models.CharField(max_length=100)),
                ('location', models.CharField(choices=[('USA', 'USA'), ('Germany', 'Germany'), ('Pakistan', 'Pakistan'), ('Remote', 'Remote'), ('UK', 'UK'), ('Canada', 'Canada')], default='Remote', max_length=20)),
                ('skills_required', models.CharField(max_length=255)),
                ('deadline', models.DateField()),
                ('description', models.TextField()),
                ('stipend', models.IntegerField(blank=True, help_text='Stipend in local currency (500-1500)', null=True, validators=[django.core.validators.MinValueValidator(500), django.core.validators.MaxValueValidator(1500)])),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='HackathonEnrollment',
            fields=[
                ('enrollment_id', models.AutoField(primary_key=True, serialize=False)),
                ('participation_type', models.CharField(choices=[('solo', 'Solo'), ('team', 'Team')], max_length=10)),
                ('participant_name', models.CharField(max_length=200)),
                ('team_name', models.CharField(blank=True, default='', max_length=200)),
                ('skills', models.TextField()),
                ('enrollment_date', models.DateTimeField(auto_now_add=True)),
                ('hackathon', models.ForeignKey(db_column='hackathon_id', on_delete=django.db.models.deletion.CASCADE, to='CareerCompassapp.hackathon')),
            ],
            options={
                'db_table': 'hackathon_enrollment',
            },
        ),
        migrations.CreateModel(
            name='InternshipApplication',
            fields=[
                ('application_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('applied_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('internship', models.ForeignKey(db_column='internship_id', on_delete=django.db.models.deletion.CASCADE, to='CareerCompassapp.internships')),
            ],
            options={
                'db_table': 'internship_applications',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('member_id', models.AutoField(primary_key=True, serialize=False)),
                ('member_name', models.CharField(max_length=200)),
                ('member_skills', models.TextField(blank=True, default='')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='CareerCompassapp.hackathonenrollment')),
            ],
            options={
                'db_table': 'team_members',
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_time', models.DateTimeField(blank=True, null=True)),
                ('logout_time', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=100)),
                ('device_info', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
